#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BotFactory_TargetDummy

#include "Basic.hpp"

#include "BP_BotFactory_TargetDummy_classes.hpp"
#include "BP_BotFactory_TargetDummy_parameters.hpp"


namespace SDK
{

// Function BP_BotFactory_TargetDummy.BP_BotFactory_TargetDummy_C.AttachAndBindTargetDummyToBot
// (Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Interactable_TargetDummy_C*   TargetDummy_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AHWCharacter_Base*                ProxyCharacter                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_BotFactory_TargetDummy_C::AttachAndBindTargetDummyToBot(class ABP_Interactable_TargetDummy_C* TargetDummy_0, class AHWCharacter_Base* ProxyCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BotFactory_TargetDummy_C", "AttachAndBindTargetDummyToBot");

	Params::BP_BotFactory_TargetDummy_C_AttachAndBindTargetDummyToBot Parms{};

	Parms.TargetDummy_0 = TargetDummy_0;
	Parms.ProxyCharacter = ProxyCharacter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BotFactory_TargetDummy.BP_BotFactory_TargetDummy_C.Cleanup
// (Protected, BlueprintCallable, BlueprintEvent)

void ABP_BotFactory_TargetDummy_C::Cleanup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BotFactory_TargetDummy_C", "Cleanup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BotFactory_TargetDummy.BP_BotFactory_TargetDummy_C.CreateInteractable
// (Protected, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SpawnedBot                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_BotFactory_TargetDummy_C::CreateInteractable(class AActor* SpawnedBot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BotFactory_TargetDummy_C", "CreateInteractable");

	Params::BP_BotFactory_TargetDummy_C_CreateInteractable Parms{};

	Parms.SpawnedBot = SpawnedBot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BotFactory_TargetDummy.BP_BotFactory_TargetDummy_C.CycleTargetDummyPawn
// (BlueprintCallable, BlueprintEvent)

void ABP_BotFactory_TargetDummy_C::CycleTargetDummyPawn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BotFactory_TargetDummy_C", "CycleTargetDummyPawn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BotFactory_TargetDummy.BP_BotFactory_TargetDummy_C.ExecuteUbergraph_BP_BotFactory_TargetDummy
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BotFactory_TargetDummy_C::ExecuteUbergraph_BP_BotFactory_TargetDummy(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BotFactory_TargetDummy_C", "ExecuteUbergraph_BP_BotFactory_TargetDummy");

	Params::BP_BotFactory_TargetDummy_C_ExecuteUbergraph_BP_BotFactory_TargetDummy Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BotFactory_TargetDummy.BP_BotFactory_TargetDummy_C.ManualRespawn
// (Protected, BlueprintCallable, BlueprintEvent)

void ABP_BotFactory_TargetDummy_C::ManualRespawn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BotFactory_TargetDummy_C", "ManualRespawn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BotFactory_TargetDummy.BP_BotFactory_TargetDummy_C.OnSpawnBotDied
// (Event, Public, BlueprintEvent)
// Parameters:
// class AHWCharacter_Base*                characterKilled                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Killer                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_BotFactory_TargetDummy_C::OnSpawnBotDied(class AHWCharacter_Base* characterKilled, class AActor* Killer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BotFactory_TargetDummy_C", "OnSpawnBotDied");

	Params::BP_BotFactory_TargetDummy_C_OnSpawnBotDied Parms{};

	Parms.characterKilled = characterKilled;
	Parms.Killer = Killer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BotFactory_TargetDummy.BP_BotFactory_TargetDummy_C.OnSpawnedBot
// (Event, Public, BlueprintEvent)
// Parameters:
// class AHWCharacter_Base*                characterSpawned                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_BotFactory_TargetDummy_C::OnSpawnedBot(class AHWCharacter_Base* characterSpawned)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BotFactory_TargetDummy_C", "OnSpawnedBot");

	Params::BP_BotFactory_TargetDummy_C_OnSpawnedBot Parms{};

	Parms.characterSpawned = characterSpawned;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BotFactory_TargetDummy.BP_BotFactory_TargetDummy_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ABP_BotFactory_TargetDummy_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BotFactory_TargetDummy_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}

}

