#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPE_Guide

#include "Basic.hpp"

#include "BP_NPE_Guide_classes.hpp"
#include "BP_NPE_Guide_parameters.hpp"


namespace SDK
{

// Function BP_NPE_Guide.BP_NPE_Guide_C.ExecuteUbergraph_BP_NPE_Guide
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_NPE_Guide_C::ExecuteUbergraph_BP_NPE_Guide(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPE_Guide_C", "ExecuteUbergraph_BP_NPE_Guide");

	Params::BP_NPE_Guide_C_ExecuteUbergraph_BP_NPE_Guide Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_NPE_Guide.BP_NPE_Guide_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_NPE_Guide_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPE_Guide_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_NPE_Guide.BP_NPE_Guide_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_NPE_Guide_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPE_Guide_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

