#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DLC_BumbasGoldenDagger

#include "Basic.hpp"

#include "Hemingway_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DLC_BumbasGoldenDagger.DLC_BumbasGoldenDagger_C
// 0x0000 (0x0160 - 0x0160)
class UDLC_BumbasGoldenDagger_C final : public UHWAbilityLevelConfig
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DLC_BumbasGoldenDagger_C">();
	}
	static class UDLC_BumbasGoldenDagger_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDLC_BumbasGoldenDagger_C>();
	}
};
static_assert(alignof(UDLC_BumbasGoldenDagger_C) == 0x000008, "Wrong alignment on UDLC_BumbasGoldenDagger_C");
static_assert(sizeof(UDLC_BumbasGoldenDagger_C) == 0x000160, "Wrong size on UDLC_BumbasGoldenDagger_C");

}

