#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EQuickPlayButtonMode

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EQuickPlayButtonMode.EQuickPlayButtonMode
// NumValues: 0x0004
enum class EQuickPlayButtonMode : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	EQuickPlayButtonMode_MAX                 = 3,
};

}

