#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Items_Necronomicon

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Hemingway_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Items_Necronomicon.GA_Items_Necronomicon_C
// 0x0008 (0x0EE0 - 0x0ED8)
class UGA_Items_Necronomicon_C final : public UHWAbility_PassiveItem
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0ED8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_Items_Necronomicon(int32 EntryPoint);
	void OnAvatarDied(const struct FDamageEventData& DeathEventData);
	void ProvideAssistBuff(class AHWTeamState* Team, class AHWPlayerState* TeamMember, const struct FAssistEventData& AssistEventData);
	void ProvideKillBuff(class AHWTeamState* Team, class AHWPlayerState* TeamMember, const struct FDamageEventData& KillEventData);
	void SetupListeners();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Items_Necronomicon_C">();
	}
	static class UGA_Items_Necronomicon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Items_Necronomicon_C>();
	}
};
static_assert(alignof(UGA_Items_Necronomicon_C) == 0x000008, "Wrong alignment on UGA_Items_Necronomicon_C");
static_assert(sizeof(UGA_Items_Necronomicon_C) == 0x000EE0, "Wrong size on UGA_Items_Necronomicon_C");
static_assert(offsetof(UGA_Items_Necronomicon_C, UberGraphFrame) == 0x000ED8, "Member 'UGA_Items_Necronomicon_C::UberGraphFrame' has a wrong offset!");

}

