#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_BreastplateOfValor_Buff

#include "Basic.hpp"

#include "Hemingway_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_BreastplateOfValor_Buff.GC_BreastplateOfValor_Buff_C
// 0x0000 (0x03B0 - 0x03B0)
class UGC_BreastplateOfValor_Buff_C final : public UHWGameplayCueNotify_Burst
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_BreastplateOfValor_Buff_C">();
	}
	static class UGC_BreastplateOfValor_Buff_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGC_BreastplateOfValor_Buff_C>();
	}
};
static_assert(alignof(UGC_BreastplateOfValor_Buff_C) == 0x000008, "Wrong alignment on UGC_BreastplateOfValor_Buff_C");
static_assert(sizeof(UGC_BreastplateOfValor_Buff_C) == 0x0003B0, "Wrong size on UGC_BreastplateOfValor_Buff_C");

}

