#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_FloatingText_GenericNumber

#include "Basic.hpp"

#include "HemingwayUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_FloatingText_GenericNumber.GC_FloatingText_GenericNumber_C
// 0x0000 (0x0040 - 0x0040)
class UGC_FloatingText_GenericNumber_C final : public UHWGameplayCueFloatingText
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_FloatingText_GenericNumber_C">();
	}
	static class UGC_FloatingText_GenericNumber_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGC_FloatingText_GenericNumber_C>();
	}
};
static_assert(alignof(UGC_FloatingText_GenericNumber_C) == 0x000008, "Wrong alignment on UGC_FloatingText_GenericNumber_C");
static_assert(sizeof(UGC_FloatingText_GenericNumber_C) == 0x000040, "Wrong size on UGC_FloatingText_GenericNumber_C");

}

