#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_RuneforgedHammer_Mark

#include "Basic.hpp"

#include "Hemingway_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_RuneforgedHammer_Mark.GC_RuneforgedHammer_Mark_C
// 0x0000 (0x0FE0 - 0x0FE0)
class AGC_RuneforgedHammer_Mark_C final : public AHWGameplayCueNotify_Looping
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_RuneforgedHammer_Mark_C">();
	}
	static class AGC_RuneforgedHammer_Mark_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_RuneforgedHammer_Mark_C>();
	}
};
static_assert(alignof(AGC_RuneforgedHammer_Mark_C) == 0x000008, "Wrong alignment on AGC_RuneforgedHammer_Mark_C");
static_assert(sizeof(AGC_RuneforgedHammer_Mark_C) == 0x000FE0, "Wrong size on AGC_RuneforgedHammer_Mark_C");

}

