#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_TowerTest_Targeter

#include "Basic.hpp"

#include "GC_TowerTest_Targeter_classes.hpp"
#include "GC_TowerTest_Targeter_parameters.hpp"


namespace SDK
{

// Function GC_TowerTest_Targeter.GC_TowerTest_Targeter_C.OnBeamTetherVisualsActivated
// (BlueprintCosmetic, Event, Protected, BlueprintCallable, BlueprintEvent)

void AGC_TowerTest_Targeter_C::OnBeamTetherVisualsActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GC_TowerTest_Targeter_C", "OnBeamTetherVisualsActivated");

	UObject::ProcessEvent(Func, nullptr);
}

}

