#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SettingsInfo_PushToTalk

#include "Basic.hpp"

#include "Hemingway_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SettingsInfo_PushToTalk.SettingsInfo_PushToTalk_C
// 0x0000 (0x0190 - 0x0190)
class USettingsInfo_PushToTalk_C final : public UHWSettingsInfo_Generic
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SettingsInfo_PushToTalk_C">();
	}
	static class USettingsInfo_PushToTalk_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USettingsInfo_PushToTalk_C>();
	}
};
static_assert(alignof(USettingsInfo_PushToTalk_C) == 0x000008, "Wrong alignment on USettingsInfo_PushToTalk_C");
static_assert(sizeof(USettingsInfo_PushToTalk_C) == 0x000190, "Wrong size on USettingsInfo_PushToTalk_C");

}

