#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CommandButton

#include "Basic.hpp"

#include "WBP_CommandButton_classes.hpp"
#include "WBP_CommandButton_parameters.hpp"


namespace SDK
{

// Function WBP_CommandButton.WBP_CommandButton_C.BndEvt__WBP_Debug_General_PlayableGod_HitBox_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_CommandButton_C::BndEvt__WBP_Debug_General_PlayableGod_HitBox_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CommandButton_C", "BndEvt__WBP_Debug_General_PlayableGod_HitBox_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CommandButton.WBP_CommandButton_C.ExecuteUbergraph_WBP_CommandButton
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CommandButton_C::ExecuteUbergraph_WBP_CommandButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CommandButton_C", "ExecuteUbergraph_WBP_CommandButton");

	Params::WBP_CommandButton_C_ExecuteUbergraph_WBP_CommandButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CommandButton.WBP_CommandButton_C.Initialize
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    CommandName_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    Command_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_CommandButton_C::Initialize(const class FString& CommandName_0, const class FString& Command_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CommandButton_C", "Initialize");

	Params::WBP_CommandButton_C_Initialize Parms{};

	Parms.CommandName_0 = std::move(CommandName_0);
	Parms.Command_0 = std::move(Command_0);

	UObject::ProcessEvent(Func, &Parms);
}

}

