#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_G_V1_InteractPrompt

#include "Basic.hpp"

#include "WBP_G_V1_InteractPrompt_classes.hpp"
#include "WBP_G_V1_InteractPrompt_parameters.hpp"


namespace SDK
{

// Function WBP_G_V1_InteractPrompt.WBP_G_V1_InteractPrompt_C.EndCooldownTimer
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_G_V1_InteractPrompt_C::EndCooldownTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V1_InteractPrompt_C", "EndCooldownTimer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_G_V1_InteractPrompt.WBP_G_V1_InteractPrompt_C.EndInteractionTimer
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_G_V1_InteractPrompt_C::EndInteractionTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V1_InteractPrompt_C", "EndInteractionTimer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_G_V1_InteractPrompt.WBP_G_V1_InteractPrompt_C.ExecuteUbergraph_WBP_G_V1_InteractPrompt
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_G_V1_InteractPrompt_C::ExecuteUbergraph_WBP_G_V1_InteractPrompt(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V1_InteractPrompt_C", "ExecuteUbergraph_WBP_G_V1_InteractPrompt");

	Params::WBP_G_V1_InteractPrompt_C_ExecuteUbergraph_WBP_G_V1_InteractPrompt Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_G_V1_InteractPrompt.WBP_G_V1_InteractPrompt_C.ForceInvalidation
// (BlueprintCallable, BlueprintEvent)

void UWBP_G_V1_InteractPrompt_C::ForceInvalidation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V1_InteractPrompt_C", "ForceInvalidation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_G_V1_InteractPrompt.WBP_G_V1_InteractPrompt_C.Get_Icon_Visibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_G_V1_InteractPrompt_C::Get_Icon_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V1_InteractPrompt_C", "Get_Icon_Visibility");

	Params::WBP_G_V1_InteractPrompt_C_Get_Icon_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_G_V1_InteractPrompt.WBP_G_V1_InteractPrompt_C.Get_Lockout_Visibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_G_V1_InteractPrompt_C::Get_Lockout_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V1_InteractPrompt_C", "Get_Lockout_Visibility");

	Params::WBP_G_V1_InteractPrompt_C_Get_Lockout_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_G_V1_InteractPrompt.WBP_G_V1_InteractPrompt_C.GetCooldownPercent
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UWBP_G_V1_InteractPrompt_C::GetCooldownPercent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V1_InteractPrompt_C", "GetCooldownPercent");

	Params::WBP_G_V1_InteractPrompt_C_GetCooldownPercent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_G_V1_InteractPrompt.WBP_G_V1_InteractPrompt_C.GetCooldownText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_G_V1_InteractPrompt_C::GetCooldownText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V1_InteractPrompt_C", "GetCooldownText");

	Params::WBP_G_V1_InteractPrompt_C_GetCooldownText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_G_V1_InteractPrompt.WBP_G_V1_InteractPrompt_C.GetInteractionPercent
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UWBP_G_V1_InteractPrompt_C::GetInteractionPercent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V1_InteractPrompt_C", "GetInteractionPercent");

	Params::WBP_G_V1_InteractPrompt_C_GetInteractionPercent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_G_V1_InteractPrompt.WBP_G_V1_InteractPrompt_C.GetInteractionProgressText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_G_V1_InteractPrompt_C::GetInteractionProgressText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V1_InteractPrompt_C", "GetInteractionProgressText");

	Params::WBP_G_V1_InteractPrompt_C_GetInteractionProgressText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_G_V1_InteractPrompt.WBP_G_V1_InteractPrompt_C.InitializeWidget
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_G_V1_InteractPrompt_C::InitializeWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V1_InteractPrompt_C", "InitializeWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_G_V1_InteractPrompt.WBP_G_V1_InteractPrompt_C.OnShown
// (Event, Public, BlueprintEvent)

void UWBP_G_V1_InteractPrompt_C::OnShown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V1_InteractPrompt_C", "OnShown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_G_V1_InteractPrompt.WBP_G_V1_InteractPrompt_C.StartInteractionTimer
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  TotalInteractionTime_0                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_G_V1_InteractPrompt_C::StartInteractionTimer(double TotalInteractionTime_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V1_InteractPrompt_C", "StartInteractionTimer");

	Params::WBP_G_V1_InteractPrompt_C_StartInteractionTimer Parms{};

	Parms.TotalInteractionTime_0 = TotalInteractionTime_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_G_V1_InteractPrompt.WBP_G_V1_InteractPrompt_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_G_V1_InteractPrompt_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V1_InteractPrompt_C", "Tick");

	Params::WBP_G_V1_InteractPrompt_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_G_V1_InteractPrompt.WBP_G_V1_InteractPrompt_C.UninitializeWidget
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_G_V1_InteractPrompt_C::UninitializeWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V1_InteractPrompt_C", "UninitializeWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_G_V1_InteractPrompt.WBP_G_V1_InteractPrompt_C.UpdateCooldownSwitch
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  CooldownDuration                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  TotalCooldownDuration                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_G_V1_InteractPrompt_C::UpdateCooldownSwitch(double CooldownDuration, double TotalCooldownDuration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V1_InteractPrompt_C", "UpdateCooldownSwitch");

	Params::WBP_G_V1_InteractPrompt_C_UpdateCooldownSwitch Parms{};

	Parms.CooldownDuration = CooldownDuration;
	Parms.TotalCooldownDuration = TotalCooldownDuration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_G_V1_InteractPrompt.WBP_G_V1_InteractPrompt_C.UpdateLockoutSwitch
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_G_V1_InteractPrompt_C::UpdateLockoutSwitch(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V1_InteractPrompt_C", "UpdateLockoutSwitch");

	Params::WBP_G_V1_InteractPrompt_C_UpdateLockoutSwitch Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

