#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_G_Prototype_Journeys_Abilities_Start

#include "Basic.hpp"

#include "WBP_G_Prototype_Journeys_Abilities_Start_classes.hpp"
#include "WBP_G_Prototype_Journeys_Abilities_Start_parameters.hpp"


namespace SDK
{

// Function WBP_G_Prototype_Journeys_Abilities_Start.WBP_G_Prototype_Journeys_Abilities_Start_C.BndEvt__WBP_G_Prototype_Journeys_Abilities_Start_ChallengeButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_G_Prototype_Journeys_Abilities_Start_C::BndEvt__WBP_G_Prototype_Journeys_Abilities_Start_ChallengeButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_Prototype_Journeys_Abilities_Start_C", "BndEvt__WBP_G_Prototype_Journeys_Abilities_Start_ChallengeButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_G_Prototype_Journeys_Abilities_Start.WBP_G_Prototype_Journeys_Abilities_Start_C.BndEvt__WBP_G_Prototype_Journeys_Relics_HWButton_62_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_G_Prototype_Journeys_Abilities_Start_C::BndEvt__WBP_G_Prototype_Journeys_Relics_HWButton_62_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_Prototype_Journeys_Abilities_Start_C", "BndEvt__WBP_G_Prototype_Journeys_Relics_HWButton_62_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_G_Prototype_Journeys_Abilities_Start.WBP_G_Prototype_Journeys_Abilities_Start_C.ExecuteUbergraph_WBP_G_Prototype_Journeys_Abilities_Start
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_G_Prototype_Journeys_Abilities_Start_C::ExecuteUbergraph_WBP_G_Prototype_Journeys_Abilities_Start(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_Prototype_Journeys_Abilities_Start_C", "ExecuteUbergraph_WBP_G_Prototype_Journeys_Abilities_Start");

	Params::WBP_G_Prototype_Journeys_Abilities_Start_C_ExecuteUbergraph_WBP_G_Prototype_Journeys_Abilities_Start Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

