#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_C_HomeQuestDisplayEntry

#include "Basic.hpp"

#include "WBP_C_HomeQuestDisplayEntry_classes.hpp"
#include "WBP_C_HomeQuestDisplayEntry_parameters.hpp"


namespace SDK
{

// Function WBP_C_HomeQuestDisplayEntry.WBP_C_HomeQuestDisplayEntry_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UWBP_C_HomeQuestDisplayEntry_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_C_HomeQuestDisplayEntry_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_C_HomeQuestDisplayEntry.WBP_C_HomeQuestDisplayEntry_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_C_HomeQuestDisplayEntry_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_C_HomeQuestDisplayEntry_C", "BP_OnItemExpansionChanged");

	Params::WBP_C_HomeQuestDisplayEntry_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_C_HomeQuestDisplayEntry.WBP_C_HomeQuestDisplayEntry_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_C_HomeQuestDisplayEntry_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_C_HomeQuestDisplayEntry_C", "BP_OnItemSelectionChanged");

	Params::WBP_C_HomeQuestDisplayEntry_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_C_HomeQuestDisplayEntry.WBP_C_HomeQuestDisplayEntry_C.ExecuteUbergraph_WBP_C_HomeQuestDisplayEntry
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_C_HomeQuestDisplayEntry_C::ExecuteUbergraph_WBP_C_HomeQuestDisplayEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_C_HomeQuestDisplayEntry_C", "ExecuteUbergraph_WBP_C_HomeQuestDisplayEntry");

	Params::WBP_C_HomeQuestDisplayEntry_C_ExecuteUbergraph_WBP_C_HomeQuestDisplayEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_C_HomeQuestDisplayEntry.WBP_C_HomeQuestDisplayEntry_C.OnDisplayFailedInfo
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_C_HomeQuestDisplayEntry_C::OnDisplayFailedInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_C_HomeQuestDisplayEntry_C", "OnDisplayFailedInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_C_HomeQuestDisplayEntry.WBP_C_HomeQuestDisplayEntry_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_C_HomeQuestDisplayEntry_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_C_HomeQuestDisplayEntry_C", "OnListItemObjectSet");

	Params::WBP_C_HomeQuestDisplayEntry_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_C_HomeQuestDisplayEntry.WBP_C_HomeQuestDisplayEntry_C.OnQuestClaimed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_C_HomeQuestDisplayEntry_C::OnQuestClaimed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_C_HomeQuestDisplayEntry_C", "OnQuestClaimed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_C_HomeQuestDisplayEntry.WBP_C_HomeQuestDisplayEntry_C.OnQuestInfoFail
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bShouldSelfRemove                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_C_HomeQuestDisplayEntry_C::OnQuestInfoFail(bool bShouldSelfRemove)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_C_HomeQuestDisplayEntry_C", "OnQuestInfoFail");

	Params::WBP_C_HomeQuestDisplayEntry_C_OnQuestInfoFail Parms{};

	Parms.bShouldSelfRemove = bShouldSelfRemove;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_C_HomeQuestDisplayEntry.WBP_C_HomeQuestDisplayEntry_C.OnUpdateQuestData
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class UHWQuest*                   QuestData                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_C_HomeQuestDisplayEntry_C::OnUpdateQuestData(const class UHWQuest* QuestData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_C_HomeQuestDisplayEntry_C", "OnUpdateQuestData");

	Params::WBP_C_HomeQuestDisplayEntry_C_OnUpdateQuestData Parms{};

	Parms.QuestData = QuestData;

	UObject::ProcessEvent(Func, &Parms);
}

}

