#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Social_Header_Cosmetic

#include "Basic.hpp"

#include "WBP_Social_Header_Cosmetic_classes.hpp"
#include "WBP_Social_Header_Cosmetic_parameters.hpp"


namespace SDK
{

// Function WBP_Social_Header_Cosmetic.WBP_Social_Header_Cosmetic_C.BindContextMenu
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Social_Header_Cosmetic_C::BindContextMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Social_Header_Cosmetic_C", "BindContextMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Social_Header_Cosmetic.WBP_Social_Header_Cosmetic_C.BndEvt__DNDToggleBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_Social_Header_Cosmetic_C::BndEvt__DNDToggleBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Social_Header_Cosmetic_C", "BndEvt__DNDToggleBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Social_Header_Cosmetic.WBP_Social_Header_Cosmetic_C.ExecuteUbergraph_WBP_Social_Header_Cosmetic
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Social_Header_Cosmetic_C::ExecuteUbergraph_WBP_Social_Header_Cosmetic(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Social_Header_Cosmetic_C", "ExecuteUbergraph_WBP_Social_Header_Cosmetic");

	Params::WBP_Social_Header_Cosmetic_C_ExecuteUbergraph_WBP_Social_Header_Cosmetic Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Social_Header_Cosmetic.WBP_Social_Header_Cosmetic_C.HandleInputStateChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ERH_INPUT_STATE                         InputState                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Social_Header_Cosmetic_C::HandleInputStateChanged(ERH_INPUT_STATE InputState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Social_Header_Cosmetic_C", "HandleInputStateChanged");

	Params::WBP_Social_Header_Cosmetic_C_HandleInputStateChanged Parms{};

	Parms.InputState = InputState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Social_Header_Cosmetic.WBP_Social_Header_Cosmetic_C.HandleMenuHidden
// (BlueprintCallable, BlueprintEvent)

void UWBP_Social_Header_Cosmetic_C::HandleMenuHidden()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Social_Header_Cosmetic_C", "HandleMenuHidden");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Social_Header_Cosmetic.WBP_Social_Header_Cosmetic_C.HandleMenuStart
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_PlayerStatus_ContextMenuOption_C*FocusWidget                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Social_Header_Cosmetic_C::HandleMenuStart(class UWBP_PlayerStatus_ContextMenuOption_C* FocusWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Social_Header_Cosmetic_C", "HandleMenuStart");

	Params::WBP_Social_Header_Cosmetic_C_HandleMenuStart Parms{};

	Parms.FocusWidget = FocusWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Social_Header_Cosmetic.WBP_Social_Header_Cosmetic_C.HandleReadyNavigation
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UWBP_PlayerStatus_ContextMenuOption_C*>&StatusButtons                                          (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UWBP_Social_Header_Cosmetic_C::HandleReadyNavigation(TArray<class UWBP_PlayerStatus_ContextMenuOption_C*>& StatusButtons)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Social_Header_Cosmetic_C", "HandleReadyNavigation");

	Params::WBP_Social_Header_Cosmetic_C_HandleReadyNavigation Parms{};

	Parms.StatusButtons = std::move(StatusButtons);

	UObject::ProcessEvent(Func, &Parms);

	StatusButtons = std::move(Parms.StatusButtons);
}


// Function WBP_Social_Header_Cosmetic.WBP_Social_Header_Cosmetic_C.HideStatusMenu
// (BlueprintCallable, BlueprintEvent)

void UWBP_Social_Header_Cosmetic_C::HideStatusMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Social_Header_Cosmetic_C", "HideStatusMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Social_Header_Cosmetic.WBP_Social_Header_Cosmetic_C.InitializeWidget
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_Social_Header_Cosmetic_C::InitializeWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Social_Header_Cosmetic_C", "InitializeWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Social_Header_Cosmetic.WBP_Social_Header_Cosmetic_C.OnGetPlayerPlatform
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ERHPlatformDisplayType                  PlatformType                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Social_Header_Cosmetic_C::OnGetPlayerPlatform(ERHPlatformDisplayType PlatformType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Social_Header_Cosmetic_C", "OnGetPlayerPlatform");

	Params::WBP_Social_Header_Cosmetic_C_OnGetPlayerPlatform Parms{};

	Parms.PlatformType = PlatformType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Social_Header_Cosmetic.WBP_Social_Header_Cosmetic_C.PlayClickSFX
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Social_Header_Cosmetic_C::PlayClickSFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Social_Header_Cosmetic_C", "PlayClickSFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Social_Header_Cosmetic.WBP_Social_Header_Cosmetic_C.SetData
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class URH_PlayerInfo*                   PlayerInfo                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Social_Header_Cosmetic_C::SetData(class URH_PlayerInfo* PlayerInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Social_Header_Cosmetic_C", "SetData");

	Params::WBP_Social_Header_Cosmetic_C_SetData Parms{};

	Parms.PlayerInfo = PlayerInfo;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Social_Header_Cosmetic.WBP_Social_Header_Cosmetic_C.ToggleDND
// (BlueprintCallable, BlueprintEvent)

void UWBP_Social_Header_Cosmetic_C::ToggleDND()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Social_Header_Cosmetic_C", "ToggleDND");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Social_Header_Cosmetic.WBP_Social_Header_Cosmetic_C.UninitializeWidget
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_Social_Header_Cosmetic_C::UninitializeWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Social_Header_Cosmetic_C", "UninitializeWidget");

	UObject::ProcessEvent(Func, nullptr);
}

}

