#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_G_V2_ObjectiveHealthbar_Generic

#include "Basic.hpp"

#include "WBP_G_V2_ObjectiveHealthbar_Generic_classes.hpp"
#include "WBP_G_V2_ObjectiveHealthbar_Generic_parameters.hpp"


namespace SDK
{

// Function WBP_G_V2_ObjectiveHealthbar_Generic.WBP_G_V2_ObjectiveHealthbar_Generic_C.ExecuteUbergraph_WBP_G_V2_ObjectiveHealthbar_Generic
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_G_V2_ObjectiveHealthbar_Generic_C::ExecuteUbergraph_WBP_G_V2_ObjectiveHealthbar_Generic(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V2_ObjectiveHealthbar_Generic_C", "ExecuteUbergraph_WBP_G_V2_ObjectiveHealthbar_Generic");

	Params::WBP_G_V2_ObjectiveHealthbar_Generic_C_ExecuteUbergraph_WBP_G_V2_ObjectiveHealthbar_Generic Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_G_V2_ObjectiveHealthbar_Generic.WBP_G_V2_ObjectiveHealthbar_Generic_C.HandleTowerDestructionEvent
// (Protected, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Stage                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_G_V2_ObjectiveHealthbar_Generic_C::HandleTowerDestructionEvent(int32 Stage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V2_ObjectiveHealthbar_Generic_C", "HandleTowerDestructionEvent");

	Params::WBP_G_V2_ObjectiveHealthbar_Generic_C_HandleTowerDestructionEvent Parms{};

	Parms.Stage = Stage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_G_V2_ObjectiveHealthbar_Generic.WBP_G_V2_ObjectiveHealthbar_Generic_C.OnDestructionStageReached
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Stage                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    FinalStage                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_G_V2_ObjectiveHealthbar_Generic_C::OnDestructionStageReached(int32 Stage, bool FinalStage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V2_ObjectiveHealthbar_Generic_C", "OnDestructionStageReached");

	Params::WBP_G_V2_ObjectiveHealthbar_Generic_C_OnDestructionStageReached Parms{};

	Parms.Stage = Stage;
	Parms.FinalStage = FinalStage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_G_V2_ObjectiveHealthbar_Generic.WBP_G_V2_ObjectiveHealthbar_Generic_C.OnHide
// (Event, Public, BlueprintEvent)

void UWBP_G_V2_ObjectiveHealthbar_Generic_C::OnHide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V2_ObjectiveHealthbar_Generic_C", "OnHide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_G_V2_ObjectiveHealthbar_Generic.WBP_G_V2_ObjectiveHealthbar_Generic_C.OnShown
// (Event, Public, BlueprintEvent)

void UWBP_G_V2_ObjectiveHealthbar_Generic_C::OnShown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V2_ObjectiveHealthbar_Generic_C", "OnShown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_G_V2_ObjectiveHealthbar_Generic.WBP_G_V2_ObjectiveHealthbar_Generic_C.OnTowerCanNoLongerSpawnFinalReward
// (BlueprintCallable, BlueprintEvent)

void UWBP_G_V2_ObjectiveHealthbar_Generic_C::OnTowerCanNoLongerSpawnFinalReward()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V2_ObjectiveHealthbar_Generic_C", "OnTowerCanNoLongerSpawnFinalReward");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_G_V2_ObjectiveHealthbar_Generic.WBP_G_V2_ObjectiveHealthbar_Generic_C.SetCharacterDisplay
// (Event, Protected, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class AHWCharacter_Base*          Character                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const class UHWCharacterItem*           CharacterItem                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_G_V2_ObjectiveHealthbar_Generic_C::SetCharacterDisplay(const class AHWCharacter_Base* Character, const class UHWCharacterItem* CharacterItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V2_ObjectiveHealthbar_Generic_C", "SetCharacterDisplay");

	Params::WBP_G_V2_ObjectiveHealthbar_Generic_C_SetCharacterDisplay Parms{};

	Parms.Character = Character;
	Parms.CharacterItem = CharacterItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_G_V2_ObjectiveHealthbar_Generic.WBP_G_V2_ObjectiveHealthbar_Generic_C.SetFinalPipVisibility
// (Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_NPC_Tower_C*                  Tower                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_G_V2_ObjectiveHealthbar_Generic_C::SetFinalPipVisibility(class ABP_NPC_Tower_C* Tower)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V2_ObjectiveHealthbar_Generic_C", "SetFinalPipVisibility");

	Params::WBP_G_V2_ObjectiveHealthbar_Generic_C_SetFinalPipVisibility Parms{};

	Parms.Tower = Tower;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_G_V2_ObjectiveHealthbar_Generic.WBP_G_V2_ObjectiveHealthbar_Generic_C.SetHealthSegmentsBrush
// (Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_G_V2_ObjectiveHealthbar_Generic_C::SetHealthSegmentsBrush(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V2_ObjectiveHealthbar_Generic_C", "SetHealthSegmentsBrush");

	Params::WBP_G_V2_ObjectiveHealthbar_Generic_C_SetHealthSegmentsBrush Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_G_V2_ObjectiveHealthbar_Generic.WBP_G_V2_ObjectiveHealthbar_Generic_C.SetPipVisibility
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_G_V2_ObjectiveHealthbar_Generic_C::SetPipVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V2_ObjectiveHealthbar_Generic_C", "SetPipVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_G_V2_ObjectiveHealthbar_Generic.WBP_G_V2_ObjectiveHealthbar_Generic_C.SetPipWrapperVisibility
// (Protected, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   LastIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AHWCharacter_Base*                Tower                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_G_V2_ObjectiveHealthbar_Generic_C::SetPipWrapperVisibility(int32 LastIndex, class AHWCharacter_Base* Tower)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V2_ObjectiveHealthbar_Generic_C", "SetPipWrapperVisibility");

	Params::WBP_G_V2_ObjectiveHealthbar_Generic_C_SetPipWrapperVisibility Parms{};

	Parms.LastIndex = LastIndex;
	Parms.Tower = Tower;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_G_V2_ObjectiveHealthbar_Generic.WBP_G_V2_ObjectiveHealthbar_Generic_C.ShowOrHidePrototypeStuff
// (Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AHWCharacter_Base*                Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_G_V2_ObjectiveHealthbar_Generic_C::ShowOrHidePrototypeStuff(class AHWCharacter_Base* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V2_ObjectiveHealthbar_Generic_C", "ShowOrHidePrototypeStuff");

	Params::WBP_G_V2_ObjectiveHealthbar_Generic_C_ShowOrHidePrototypeStuff Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_G_V2_ObjectiveHealthbar_Generic.WBP_G_V2_ObjectiveHealthbar_Generic_C.GetAttributeWidgets
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// TArray<class UHWGameplayAttributeWidget*>ReturnValue                                            (Parm, OutParm, ReturnParm, ContainsInstancedReference)

TArray<class UHWGameplayAttributeWidget*> UWBP_G_V2_ObjectiveHealthbar_Generic_C::GetAttributeWidgets() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_G_V2_ObjectiveHealthbar_Generic_C", "GetAttributeWidgets");

	Params::WBP_G_V2_ObjectiveHealthbar_Generic_C_GetAttributeWidgets Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

