#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_S_GodBuilder_ItemsList

#include "Basic.hpp"

#include "WBP_S_GodBuilder_ItemsList_classes.hpp"
#include "WBP_S_GodBuilder_ItemsList_parameters.hpp"


namespace SDK
{

// Function WBP_S_GodBuilder_ItemsList.WBP_S_GodBuilder_ItemsList_C.BndEvt__WBP_S_GodBuilder_ItemsList_SearchTextBox_K2Node_ComponentBoundEvent_1_OnEditableTextBoxCommittedEvent__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// ETextCommit                             CommitMethod                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_S_GodBuilder_ItemsList_C::BndEvt__WBP_S_GodBuilder_ItemsList_SearchTextBox_K2Node_ComponentBoundEvent_1_OnEditableTextBoxCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_S_GodBuilder_ItemsList_C", "BndEvt__WBP_S_GodBuilder_ItemsList_SearchTextBox_K2Node_ComponentBoundEvent_1_OnEditableTextBoxCommittedEvent__DelegateSignature");

	Params::WBP_S_GodBuilder_ItemsList_C_BndEvt__WBP_S_GodBuilder_ItemsList_SearchTextBox_K2Node_ComponentBoundEvent_1_OnEditableTextBoxCommittedEvent__DelegateSignature Parms{};

	Parms.Text = std::move(Text);
	Parms.CommitMethod = CommitMethod;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_S_GodBuilder_ItemsList.WBP_S_GodBuilder_ItemsList_C.ClearSearchText
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_S_GodBuilder_ItemsList_C::ClearSearchText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_S_GodBuilder_ItemsList_C", "ClearSearchText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_S_GodBuilder_ItemsList.WBP_S_GodBuilder_ItemsList_C.ExecuteUbergraph_WBP_S_GodBuilder_ItemsList
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_S_GodBuilder_ItemsList_C::ExecuteUbergraph_WBP_S_GodBuilder_ItemsList(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_S_GodBuilder_ItemsList_C", "ExecuteUbergraph_WBP_S_GodBuilder_ItemsList");

	Params::WBP_S_GodBuilder_ItemsList_C_ExecuteUbergraph_WBP_S_GodBuilder_ItemsList Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_S_GodBuilder_ItemsList.WBP_S_GodBuilder_ItemsList_C.InitializeWidget
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_S_GodBuilder_ItemsList_C::InitializeWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_S_GodBuilder_ItemsList_C", "InitializeWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_S_GodBuilder_ItemsList.WBP_S_GodBuilder_ItemsList_C.UninitializeWidget
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_S_GodBuilder_ItemsList_C::UninitializeWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_S_GodBuilder_ItemsList_C", "UninitializeWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_S_GodBuilder_ItemsList.WBP_S_GodBuilder_ItemsList_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_S_GodBuilder_ItemsList_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_S_GodBuilder_ItemsList_C", "BP_GetDesiredFocusTarget");

	Params::WBP_S_GodBuilder_ItemsList_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

