#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Debug_General_DevHUD

#include "Basic.hpp"

#include "WBP_Debug_General_DevHUD_classes.hpp"
#include "WBP_Debug_General_DevHUD_parameters.hpp"


namespace SDK
{

// Function WBP_Debug_General_DevHUD.WBP_Debug_General_DevHUD_C.BndEvt__WBP_Debug_General_PlayableGod_HitBox_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_Debug_General_DevHUD_C::BndEvt__WBP_Debug_General_PlayableGod_HitBox_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Debug_General_DevHUD_C", "BndEvt__WBP_Debug_General_PlayableGod_HitBox_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Debug_General_DevHUD.WBP_Debug_General_DevHUD_C.ExecuteUbergraph_WBP_Debug_General_DevHUD
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Debug_General_DevHUD_C::ExecuteUbergraph_WBP_Debug_General_DevHUD(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Debug_General_DevHUD_C", "ExecuteUbergraph_WBP_Debug_General_DevHUD");

	Params::WBP_Debug_General_DevHUD_C_ExecuteUbergraph_WBP_Debug_General_DevHUD Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Debug_General_DevHUD.WBP_Debug_General_DevHUD_C.SetDevHUDName
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             InDevHUDName                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Debug_General_DevHUD_C::SetDevHUDName(class FName InDevHUDName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Debug_General_DevHUD_C", "SetDevHUDName");

	Params::WBP_Debug_General_DevHUD_C_SetDevHUDName Parms{};

	Parms.InDevHUDName = InDevHUDName;

	UObject::ProcessEvent(Func, &Parms);
}

}

