#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_C_SeasonRankRewards

#include "Basic.hpp"

#include "WBP_C_SeasonRankRewards_classes.hpp"
#include "WBP_C_SeasonRankRewards_parameters.hpp"


namespace SDK
{

// Function WBP_C_SeasonRankRewards.WBP_C_SeasonRankRewards_C.ExecuteUbergraph_WBP_C_SeasonRankRewards
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_C_SeasonRankRewards_C::ExecuteUbergraph_WBP_C_SeasonRankRewards(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_C_SeasonRankRewards_C", "ExecuteUbergraph_WBP_C_SeasonRankRewards");

	Params::WBP_C_SeasonRankRewards_C_ExecuteUbergraph_WBP_C_SeasonRankRewards Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_C_SeasonRankRewards.WBP_C_SeasonRankRewards_C.OnHide
// (Event, Public, BlueprintEvent)

void UWBP_C_SeasonRankRewards_C::OnHide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_C_SeasonRankRewards_C", "OnHide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_C_SeasonRankRewards.WBP_C_SeasonRankRewards_C.OnShown
// (Event, Public, BlueprintEvent)

void UWBP_C_SeasonRankRewards_C::OnShown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_C_SeasonRankRewards_C", "OnShown");

	UObject::ProcessEvent(Func, nullptr);
}

}

