#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_QuickPlay_QueueTypeHeader

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_QuickPlay_QueueTypeHeader.WBP_QuickPlay_QueueTypeHeader_C
// 0x0010 (0x02D0 - 0x02C0)
class UWBP_QuickPlay_QueueTypeHeader_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             QueueType;                                         // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_WBP_QuickPlay_QueueTypeHeader(int32 EntryPoint);
	void SetHeaderText(const class FText& QueueType_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_QuickPlay_QueueTypeHeader_C">();
	}
	static class UWBP_QuickPlay_QueueTypeHeader_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_QuickPlay_QueueTypeHeader_C>();
	}
};
static_assert(alignof(UWBP_QuickPlay_QueueTypeHeader_C) == 0x000008, "Wrong alignment on UWBP_QuickPlay_QueueTypeHeader_C");
static_assert(sizeof(UWBP_QuickPlay_QueueTypeHeader_C) == 0x0002D0, "Wrong size on UWBP_QuickPlay_QueueTypeHeader_C");
static_assert(offsetof(UWBP_QuickPlay_QueueTypeHeader_C, UberGraphFrame) == 0x0002C0, "Member 'UWBP_QuickPlay_QueueTypeHeader_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_QuickPlay_QueueTypeHeader_C, QueueType) == 0x0002C8, "Member 'UWBP_QuickPlay_QueueTypeHeader_C::QueueType' has a wrong offset!");

}

